### ISSUE TITLE
Opening Password-Protected PDF Crashes App in iOS 9

### ISSUE THREAD

**Issue by doctorc** [vfr/Reader#123]
In iOS 9 Beta 5 (Xcode 7 Beta 6) opening of password-protected PDFs now crashes the Reader App.  There is no problem with non-password-protected PDFs.  The bug is here:

//line 90 in CGPDFDocument.m ->
CGPDFDocumentRef thePDFDocRef = CGPDFDocumentCreateWithURL(theURL);  
In iOS 9, this line returns nil for password-protected PDFs.

**Comment by zhouhao27** [comment]
I got the exactly the same problem. You solve the problem already? Thanks

**Comment by doctorc** [comment]
I believe this is a bug in xcode.  I have submitted a bug report to Apple.

**Comment by doctorc** [comment]
See my follow-up comment in github.

Sent from my iPad

On Sep 4, 2015, at 2:19 AM, Zhou Hao <notifications@github.com> wrote:

I got the exactly the same problem. You solve the problem already? Thanks

**Comment by zhouhao27** [comment]
The new Xcode 7 GM seems still not solve the issue.

**Comment by doctorc** [comment]
It has been fixed in iOS 9 GM.

**Comment by zhouhao27** [comment]
Really? Maybe I should check my code again. Thanks.

**Comment by fenta23** [comment]
Hey all, 
i've still the problem with password protected files. I'm on iOS 9.1 and also on 9.2 build with xCode 7.2.
So is it still an issue?

Tested it with apples pdf viewer and with adobe pdf reader, both working but not this Reader.

Any ideas?

Greetz, Micha.

**Comment by fenta23** [comment]
Just want to push it, 

can anyone confirm that it's still an issue? The app crashes if i try to open an password protected file:
Deploytarget: 9.2
xCode 7.2


`2016-02-16 09:46:48.073 Reader[2156:901493] *** Assertion failure in -[ReaderDocument initWithFilePath:password:], /Users/michaelpfutze/Downloads/Reader-master 2/Sources/ReaderDocument.m:222
2016-02-16 09:46:48.076 Reader[2156:901493] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'CGPDFDocumentRef == NULL'
*** First throw call stack:
(0x1840c9900 0x183737f80 0x1840c97d0 0x184a3c99c 0x1000a81e0 0x1000a7c80 0x1000a256c 0x18933cdbc 0x188f605b8 0x188dee9b0 0x18933e3bc 0x188dadb58 0x188daa8dc 0x188dec820 0x188debe1c 0x188dbc4cc 0x188dba794 0x184080efc 0x184080990 0x18407e690 0x183fad680 0x1854bc088 0x188e24d90 0x1000a1420 0x183b4e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)  `

**Comment by HarithaNaveen** [comment]
Yes,I still get this error.
*** Assertion failure in -[ReaderDocument initWithFilePath:password:]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'CGPDFDocumentRef == NULL'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113709d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001127b721e objc_exception_throw + 48
	2   CoreFoundation                      0x000000011370de42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000011234c66d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   MyAppName                             0x000000010df6a165 -[ReaderDocument initWithFilePath:password:] + 853
	5   MyAppName                             0x000000010e66609c _TTOFCSo14ReaderDocumentcfT8filePathGSQSS_8passwordGSQSS__GSQS__ + 236
	6   MyAppName                             0x000000010e640f21 _TFCSo14ReaderDocumentCfT8filePathGSQSS_8passwordGSQSS__GSQS__ + 241
	7   MyAppName                             0x000000010e026d3f _TFFC7MyAppName25MyViewController26connectionDidFinishLoadingFCSo15NSURLConnectionT_U_FT_T_ + 14447
	8   MyAppName                             0x000000010e0e4b27 _TTRXFo___XFdCb___ + 39
	9   libdispatch.dylib                   0x000000011761d978 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x00000001176470cd _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001176278a4 _dispatch_main_queue_callback_4CF + 406
	12  CoreFoundation                      0x00000001136cde49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x000000011369337d __CFRunLoopRun + 2205
	14  CoreFoundation                      0x0000000113692884 CFRunLoopRunSpecific + 420
	15  GraphicsServices                    0x000000011ad54a6f GSEventRunModal + 161
	16  UIKit                               0x0000000114e3ec68 UIApplicationMain + 159
	17  MyAppName                             0x000000010dfdc57f main + 111
	18  libdyld.dylib                       0x000000011769368d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
