### ISSUE TITLE
iOS 10 memory issue

### ISSUE THREAD

**Issue by freddek** [vfr/Reader#166]
It seems that in iOS 10, despite ReaderContentPage being properly released, the memory allocated by core graphics for drawing the PDF is not released. For every page viewed the memory usage piles up and eventually results in memory warnings and ultimately a crash. This is especially noticeable in heavier PDF documents.
Any suggestions for a viable workaround?

**Comment by RandyJackson37336** [comment]
I'm going to be mad。How to solve this problem. My application has been Crashed again and again。

**Comment by freddek** [comment]
I eventually elected to create and store the document reference in the ReaderDocument object and then pass the ReaderDocument object to the ReaderContentPage instead of recreating the document reference every time when initializing a ReaderContentPage. This seems to have mitigated the memory leak issue in my heavily modified implementation of vfr Reader.

**Comment by RandyJackson37336** [comment]
Thank you! Can you tell me the detailed steps?

**Comment by olramarlo** [comment]
@freddek Did you modify ReaderContentPage itself to support instantiating using ReaderDocument?

**Comment by freddek** [comment]
@olramarlo Yes I create the "_PDFDocRef" once when instantiating the ReaderDocument and pass this reference to ReaderContentPage instead of recreating a new reference each time instantiating a ReaderContentPage.

**Comment by emersonwood** [comment]
I've spent about a day looking at this with no real solution.

I think the memory leak is coming from ReaderContentPage.m, particularly CGContextDrawPDFPage(context, _PDFPageRef); in the drawLayer function.

I've noticed that in iOS 10.0, the line CGContextDrawPDFPage(context, _PDFPageRef) increases the retain count of the _PDFPageRef property, but it doesn't increase in lower iOS versions.

This is most likely the cause for the memory leak since the retain count for _PDFPageRef never drops to 0 and won't be deallocated.

**Comment by olramarlo** [comment]
@freddek Gotcha. Thanks!

**Comment by RandyJackson37336** [comment]
Sorry，I don't understand how to modify it. Can send the modify‘s file to my email: ZhuangWeiPeng@yahoo.com.   I appreciate your help!

**Comment by vfr** [comment]
**File a bug report with Apple.**

There is a memory management bug in iOS 10.0.1 and 10.0.2 in the CGContextDrawPDFPage() function.

**Comment by timeflying** [comment]
After I upgrade to iOS 10.1.1 this problem still exists..., Does anyone solve this issue by upgrade iOS?

**Comment by emersonwood** [comment]
Still a problem for me on iOS 10.1.1 too.

**Comment by timeflying** [comment]
I  modify the code according @freddek's comment. And the problem was solved! 
```
@interface ReaderContentPage : UIView
 
-- (instancetype)initWithURL:(NSURL *)fileURL page:(NSInteger)page password:(NSString *)phrase;
+- (instancetype)initWithDocument:(CGPDFDocumentRef)thePDFDocRef page:(NSInteger)page password:(NSString *)phrase;
```

Pass CGPDFDocumentRef instead of NSURL to ReaderContentView and ReaderContentPage.

Thank you all!

**Comment by JJayet** [comment]
Awesome, thx !
Would you maybe do a PR ?

**Comment by shenchao12344** [comment]
@timeflying can you tell me how to solve this problem

**Comment by regnete** [comment]
We are using a lightly patched version of vfr reader in our cordova plugin: https://github.com/sitewaerts/cordova-plugin-document-viewer

@freddek or @timeflying: Could you please provide a pull request  containing all the necessary changes? I fully understand the root cause of the issue and your aproach to fix it. Saddly my personal C skills could be named 'absent' and we currently don't have any in house C capacities, so I have no chance to fix it on my own.

**Comment by regnete** [comment]
Fixed it. see https://github.com/sitewaerts/Reader/commit/dd5230ecdde197c5aabc9808674333809619d2bf

**Comment by PierreBresson** [comment]
@regnete I still see leaks with sitewaerts@dd5230e

**Comment by regnete** [comment]
@PierreBresson Thx. As I mentioned before my C skills are very weak. Our application crashed always after scrolling many pages in a large PDFs. With https://github.com/sitewaerts/Reader/commit/dd5230e our application doesn't crash anymore. So our problem was solved, but others may persist.

**Comment by tiagoAGA** [comment]
With me, the problem persists. Did you leave this issue completely or you will watch this again? I'm loading heavy pdf's (50Mb+)

**Comment by regnete** [comment]
My issue is closed, so I'l leave it as it is. Sorry.

We are also loading huge pdfs with > 500 pages.
